export const CHANGE_PK_PEOPLE = 'pk/CHANGE_PK_PEOPLE';
export const CHANGE_CREATE_PK_SUCCESS = 'pk/CHANGE_CREATE_PK_SUCCESS';
export const CANCEL_CREATE_PK_SUCCESS = 'pk/CANCEL_CREATE_PK_SUCCESS';
export const CHANGE_PK_DETAIL = 'pk/CHANGE_PK_DETAIL';
export const CHANGE_PK_STATE_SUCCESS = 'pk/CHANGE_PK_STATE_SUCCESS';
export const CANCEL_PK_STATE_SUCCESS = 'pk/CANCEL_PK_STATE_SUCCESS';
export const CHANGE_PK_STATE_REJECT = 'pk/CHANGE_PK_STATE_REJECT';
export const CANCEL_PK_STATE_REJECT = 'pk/CANCEL_PK_STATE_REJECT';