export const CHANGE_RANK_LIST = 'home/CHANGE_RANK_LIST';
export const CHANGE_THIS_MONTH_RANK = 'home/CHANGE_THIS_MONTH_RANK';
export const CHANGE_THIS_QUARTER_RANK = 'home/CHANGE_THIS_QUARTER_RANK';
export const CHANGE_LAST_QUARTER_RANK = 'home/CHANGE_LAST_QUARTER_RANK';
export const GET_RANKING_LIST = 'home/GET_RANKING_LIST';